### ISSUE TITLE
about | Blankj

### ISSUE THREAD

**Issue by Blankj** [Blankj/blog-comment#4]
http://blankj.com/about/ 

 About Blankj我的中文简历我的英文简历

**Comment by ForgetAll** [comment]
* 柯基
* 大辣鸡
* 你猜
* 我是 `谁`

**Comment by dragonstylecc** [comment]
你好，你的页面透明度是怎么设置的，谢谢

**Comment by Blankj** [comment]
> @dragonstylecc
> 你好，你的页面透明度是怎么设置的，谢谢

去学点css，很简单的，调试的时候找到相应的标签然后修改样式就好了。
比如文章的是
```css
.post-block {
    background:rgba(255, 255, 255, 0.75) none repeat scroll !important;
}
```
